baseURL = "https://aan-news.proffer.dev"
languageCode = "en-us"
title = "AAN World News"
theme = "aan-world-news"
enableRobotsTXT = true

[params]
  description = "AAN is a privately-owned, independent news broadcaster that provides global coverage of worldwide events and conflicts."
  subTitle = "Our World, Your News"
  logo = "/images/aan-world-news-logo.png"

[taxonomies]
  profile = "profiles"
  tag = "tags"
  category = "categories"

[menu]

  [[menu.main]]
    identifier = "asia"
    name = "Asia"
    url = "/tags/asia/"
    weight = 1
